### ISSUE TITLE
导出js文件

### ISSUE THREAD

**Issue by i5ting** [imgcook/imove#12]

**Comment by i5ting** [comment]
先给方案，出RFC，最小依赖。

**Comment by SmallStoneSK** [comment]
云端构建方案：

1. 根据项目 id 在本地创建临时文件夹，保存不同的 dsl
2. 监听 dsl 文件变化，根据 dsl 生成源码
3. 监听源码变化，build 生成打包代码，供前台下载

**Comment by SmallStoneSK** [comment]
浏览器端打包出码：

1. 使用 @imove/compile-code 对流程图 schema 进行编译，生成一个 json，key 是文件目录，value 是文件内容
2. 根据 compile 生成的 json，利用 JSZip 在浏览器端进行 zip 压缩打包，再提供文件下载

**Comment by SmallStoneSK** [comment]
浏览器端打包出码已支持，commit: 5823fbafb18e3261ff98bebf8bdb2a2b7bb5cfdc
