### ISSUE TITLE
选中边线高亮

### ISSUE THREAD

**Issue by i5ting** [imgcook/imove#25]

**Comment by SmallStoneSK** [comment]
x6 自带的 showEdgeSelectionBox 样式不够美观

**Comment by SmallStoneSK** [comment]
已解决: 03ff151ed0e2d8e3cc66185212d25ebeb38e8706

1. 监听 edge:selected / edge:mouseover，修改 edge 的颜色和粗细，表示高亮
2. 监听 edge:unselected / edge:mouseleave，恢复 edge 的默认颜色和粗细
