### ISSUE TITLE
代码编辑体验

### ISSUE THREAD

**Issue by iloveyou11** [imgcook/imove#33]
代码编辑没有智能提示，想同步在本地开发，却不好找到指定节点，因为文件名都是一长串hash名称

**Comment by SmallStoneSK** [comment]
1. 目前的编辑器组件是用的 react-ace，代码提示只能内置一些 snippet，智能提示确实不太友好。
2. 目前的方式，在本地修改文件是不会同步到浏览器端的。如果想在本地文件开发，后续计划开发 imove-vscode 插件，这样双击节点编码的时候可以直接打开对应的文件，然后编辑
3. hash 串作为文件名确实不够直观，需要进一步优化

**Comment by i5ting** [comment]
这个解释是在回避问题

**Comment by i5ting** [comment]
我看了一下，代码提示最好的是monaco。

其中 https://github.com/suren-atoyan/monaco-react 是集成最简单的，你们可以试试

**Comment by iloveyou11** [comment]
代码编辑器改为monaco-react，丰富代码智能提示

**Comment by SmallStoneSK** [comment]
改用 https://github.com/suren-atoyan/monaco-react 之后，首次加载编辑器，会看到一个 loading 界面，体感较差

**Comment by SmallStoneSK** [comment]
> 改用 https://github.com/suren-atoyan/monaco-react 之后，首次加载编辑器，会看到一个 loading 界面，体感较差

解决方案：

1. 组件 props 有提供自定义 loading 样式的勾子，可以优化 loading 样式 [参考地址](https://github.com/suren-atoyan/monaco-react#editor)
2. 组件可以提前下载 monaco sources 到本地，然后从本地加载，但是这样会增加打包体积 [参考地址](https://github.com/suren-atoyan/monaco-react#for-electron-users)
3. 结合以上两点，在优化loading样式的基础之上，@imove/core 组件首次渲染完成之后，从 CDN 上提前加载 monaco sources。等编辑器打开的时候，资源已经ready，就不会看到 loading 样式；最差情况，资源万一没有加载好，loading样式兜底

**Comment by SmallStoneSK** [comment]
编辑器配置 theme，调整样式

可以参考：
issue: https://github.com/suren-atoyan/monaco-react/issues/107
demo: https://codesandbox.io/s/monaco-editorcustom-theme-quhcg?file=/src/index.js:507-523

**Comment by SmallStoneSK** [comment]
> 编辑器配置 theme，调整样式
> 
> 可以参考：
> issue: [suren-atoyan/monaco-react#107](https://github.com/suren-atoyan/monaco-react/issues/107)
> demo: https://codesandbox.io/s/monaco-editorcustom-theme-quhcg?file=/src/index.js:507-523

已解决: 945ff513fb1620f7e0e5943e1692442eea67c2b7
引入 monokai 主题

**Comment by i5ting** [comment]
@SmallStoneSK 对的。先在monaco-react里找issue，然后确认解决方式。如果需要，可以提pr。

再确认一下，是否需要关闭这个issue
