### ISSUE TITLE
有没有交流群？

### ISSUE THREAD

**Issue by everything8** [imgcook/imove#39]

**Comment by i5ting** [comment]
稍成熟一点之后会建立的，目前是还是最小可用版本。

**Comment by i5ting** [comment]
![](https://img.alicdn.com/imgextra/i3/O1CN01dDWrGg232H8dOHraY_!!6000000007197-2-tps-859-1184.png)

**Comment by i5ting** [comment]
@everything8 已经更新到master文档了
