### ISSUE TITLE
目前windows不兼容，但是之前版本是可以的

### ISSUE THREAD

**Issue by iloveyou11** [imgcook/imove#40]
windows电脑无法使用imove，依次执行：
$ git clone git@github.com:imgcook/imove.git
$ cd imove
$ npm install
$ npm run example

显示如下：
![image](https://user-images.githubusercontent.com/33858710/103135888-c40cbb80-46f6-11eb-805c-489e033a7500.png)

打开http://localhost:3500
无法打开网页

**Comment by i5ting** [comment]
@SmallStoneSK 看一下模块

**Comment by iloveyou11** [comment]
solve
