### ISSUE TITLE
 permission denied for mkdir '/usr/local/lib/node_modules/@imove'

### ISSUE THREAD

**Issue by peishaofeng** [imgcook/imove#42]
while running npm install (without root or sudo permission), it raise exception as blow

```
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@imove'
```

why need to create a global command for a local project?

**Comment by i5ting** [comment]
this project need a service `imove -d`。you can use nvm.sh install node to user home dir. or change /package.json postinstall use sudo permission.

we will refact with umi mock @SmallStoneSK

**Comment by peishaofeng** [comment]
I've got the answer as mentioned below:

> this project need a service imove -d。you can use nvm.sh install node to user home dir. or change /package.json postinstall use sudo permission.
