### ISSUE TITLE
生成的代码如何在本地运行？

### ISSUE THREAD

**Issue by rossroma** [imgcook/imove#46]
使用`npm run example`后，IMove运行起来了，也提示b本地连接成功，如下图；
![image](https://user-images.githubusercontent.com/6183683/104257555-b0b06d00-54b8-11eb-84d8-636a50d917f1.png)
但是访问`http://127.0.0.1:3500`，没有对应的路由页面
![image](https://user-images.githubusercontent.com/6183683/104257667-ed7c6400-54b8-11eb-80e9-68d802314527.png)

**Comment by gaomAndximi** [comment]
请问怎么解决的？
