### ISSUE TITLE
How to switch from Chinese to English (or other languages) in the UI

### ISSUE THREAD

**Issue by t2hv33** [imgcook/imove#47]
Hi team,
How to switch from Chinese to English (or other languages) in the Front End. 
I know Chinese & English & Vietnamese, so I want to contribute to translating the project into these languages.
Currently I translation directly in `_imove\packages\core\src\mods\header\connectStatus\index.tsx_`
Many thanks for considering my request.

**Comment by i5ting** [comment]
this project use https://github.com/umijs/umi to build react application. more see https://umijs.org/plugins/plugin-locale

welcome pr!
