### ISSUE TITLE
下载依赖Cypress有点太慢~，是否有优化策略呢

### ISSUE THREAD

**Issue by jiangtao** [imgcook/imove#55]
如题
![image](https://user-images.githubusercontent.com/2155745/104694888-d3f04c00-5746-11eb-9784-4689bc64a16e.png)
大概30 分钟，5%

**Comment by juzhiyuan** [comment]
```sh
$ export CYPRESS_INSTALL_BINARY=0 yarn install
```

可以避免安装 Cypress（如果不需要的化

**Comment by jiangtao** [comment]
`CYPRESS_INSTALL_BINARY=0 cnpm i`
