### ISSUE TITLE
#bug#样式错乱

### ISSUE THREAD

**Issue by BinZhiZhu** [imgcook/imove#56]
![image](https://user-images.githubusercontent.com/35824900/104735353-71b23e00-577c-11eb-8473-38a649b91757.png)

刚刚run起来，左侧随机点了一个元件，即可复现

**Comment by SmallStoneSK** [comment]
@BinZhiZhu 

收到，这个应该是工具栏内容比较多，屏幕大小不够导致的，UI 适配上我们做下兼容

**Comment by LiteSun** [comment]
![image](https://user-images.githubusercontent.com/31329157/104795814-0902aa00-57ec-11eb-8d74-fde555ec35d7.png)
左侧的 `处理` 卡片也没有显示完全，也需要适配下。

**Comment by juzhiyuan** [comment]
> ![image](https://user-images.githubusercontent.com/35824900/104735353-71b23e00-577c-11eb-8473-38a649b91757.png)
> 
> 刚刚run起来，左侧随机点了一个元件，即可复现

@SmallStoneSK 这个问题在不改变 `ModifyStatus` 内容的前提下：
1. 把 `ModifyStatus` 组件更换位置，不要放在 `Toolbar`，否则会在13英寸 MBP 上显示不完整；
2. 仍然放在 `Toolbar` 中，但允许 `Toolbar` 水平滚动（不推荐），13寸 MBP 刚好显示**置于底层**的图标。

**Comment by SmallStoneSK** [comment]
已解决: 12ad13c7a8a129df1c2974308183d461c9cf57c8
