### ISSUE TITLE
在线实例无法查看，代码报错

### ISSUE THREAD

**Issue by jiangtao** [imgcook/imove#62]
如题
![image](https://user-images.githubusercontent.com/2155745/104847349-74e33080-591a-11eb-8238-13bdf14a94d4.png)

**Comment by i5ting** [comment]
@jiangtao 求复现步骤

**Comment by i5ting** [comment]
目前我这里看 https://65hzt.sse.codesandbox.io/ 是正常。

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/104879497-e9f54b00-5998-11eb-9d4a-fbf43ab6f535.png)

是否需要提供公共配置服务器？
