### ISSUE TITLE
按照指引在项目中 imove -i &  imove -d  根本没有代码保存

### ISSUE THREAD

**Issue by cereschen** [imgcook/imove#75]
只在根目录生成了一个 imove.config.js

**Comment by SmallStoneSK** [comment]
@cereschen 

代码保存到你的项目需要在流程图上触发 `ctrl + s` 快捷键

**Comment by cereschen** [comment]
> @cereschen
> 
> 代码保存到你的项目需要在流程图上触发`ctrl + s`快捷键

你好 这一步肯定是做了的 我的系统的win10 node版本12.18.2

**Comment by SmallStoneSK** [comment]
@cereschen 

1. `imove -i` 是用来初始化生成 `imove.config.js` 配置文件的，执行一次就行。

2. 确认一下 `imove -d` 是否在你的项目根目录执行？如果本地监听成功，当你在流程图上触发 `ctrl + s` 的时候，控制台会有输出，可以看下输出信息，如果成功的话，每次保存都会有如下提示 `compile successfully!`

![image](https://user-images.githubusercontent.com/17713870/105573778-ed267780-5d9a-11eb-88c1-d1012566232d.png)

**Comment by lehui521** [comment]
我的也是这种情况

**Comment by lehui521** [comment]
也运行了
