### ISSUE TITLE
支持VUE吗？

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [imgcook/imove#78]

**Comment by SmallStoneSK** [comment]
@Dean-ZhenYao-Wang  `iMove` 的出码本身不和任何框架绑定，目前就是原生的 `js`，所以 `vue` 的项目中也是可以用的。而且编排的方式只是一种思想，后面和语言也可以没关系，可以用来写 `java` 或其他语言。

**Comment by Dean-ZhenYao-Wang** [comment]
> @Dean-ZhenYao-Wang `iMove` 的出码本身不和任何框架绑定，目前就是原生的 `js`，所以 `vue` 的项目中也是可以用的。而且编排的方式只是一种思想，后面和语言也可以没关系，可以用来写 `java` 或其他语言。

您的回答解答了我的疑惑，万分感谢。
我将关闭该问题。
