### ISSUE TITLE
imove是否让前端离业务更远了

### ISSUE THREAD

**Issue by baixiaoyu2997** [imgcook/imove#81]
以我的理解，imove前期可以帮助代码更好的组织，后期可以运维直出页面？ 那么其实前端在这里起到的作用更像是一个“工具人”的作用。离业务更远，离涨薪更远？

**Comment by cbbfcd** [comment]
近十年，前端借着东风，蓬勃发展，现在的前端技术栈有能力去承接更多的业务场景，也面临着更多更复杂的需求，我以为这是利好的一面，拓宽了边界，让前端不仅仅只是切图仔，而有着无限的可能，是吧？毕竟连 tf.js，或者我厂的 paddlepaddle.js 让前端可以不转变技术语言的基础上可以接触 AI 方向内容。
当然，现在也面临着很多工作重复性太强，技术含量低，对于这种工作，很多大厂都有自己的解决方案，都在探索，「可视化」就是其中一种很直接有效的方案。
作为前端，深入业务不是技术栈左右的，即使是可视化，也得是熟知业务逻辑才可所见即所得啊。至于涨薪，这个和输出挂钩了就

**Comment by i5ting** [comment]
云计算和云原生也没有让运维死掉，只是大家转到应用或底层而已。技术演进，会对一些人有影响，但积极心态看，也是新机会的。
