### ISSUE TITLE
master分支中eslintrc.js中extends的prettier提示找不到

### ISSUE THREAD

**Issue by anitakym** [imgcook/imove#84]
output:
[Error - 11:17:21 AM] ESLint stack trace:
[Error - 11:17:21 AM] Error: Failed to load config "prettier" to extend from.

解决方法：
在package.json增加
"eslint-config-prettier": "^7.2.0"

看了下在不同的别（0.3.X， dev）的分支，有增加eslint-config-prettier 来处理extend from 找不到的问题， 但配置不太一致，不知道最后定的rules是什么？

**Comment by SmallStoneSK** [comment]
@anitakym 以 `0.3.x` 的分支为准，之前在 `0.3.x` 分支上修复了，还没有合并到 `master` 上来
